language: node_js
node_js:
- lts/*
before_script:
- npm install
notifications:
  email:
    on_success: always
deploy:
  provider: heroku
  api_key:
    secure: Fix+Wb/6/mVq7WCQeNdo4wP7lvS2c0Rd1X8DoEGd5b17YwMdxcYTDHxLvM0I/OHaljqeHGGk4+kEyOjHbRydQvuaRQiQQH7a+meBax8GgXSZ1BeaJJMiuawfuDA7wdmb3XJKyRq9dlhYfTQq05FmWsqGdWW633UqjjVXjRsTQtUqCfjW/TuVHY0iWZfux/hLVnrybGttGMQoEw8Fwv86UGpBZupb/Qp5Qg1cg1ZvQc+fzSYeu3YLdbuBbdRJbwn5nhjc9DYT3V6uYm3a2dhPRRCJDuJt8KkMpxFe0c2q8jRjLD6UA6LbUBT+sR7w095GY3oXFdwbullOc70RSIDkvWcZ1Q02y083588fznvHkLfGds3kRd7c6JkcrHUu3PoZ6zT2o7EHFz4w57l1tInO3g+9QwDX2R2QSIe14Tok7BHnGcQYTsiS7lkdG+4WXzSLZ8yrc1osnbCbgmLvb3/8r0I4oUzDbJD0YJosBxkqTpRRpqIfd2wX1leNQNw6sZL3rLqt5JpkCqhwodVQxvUq1DU3xnIBuZCwdDG/wjTTCtUrR56FHLTYaSQ+5mpP453Vvchxe2+0vMmF2atmvrPeB/zxb4gsoWLtFCGNsUd38R/UfNkTkHD7k1Hbw5GzHNh3dAWfkHpgqvbih/8qXqJ9JvxA3g6eUyCOkgrPV+08Nk4=
  skip_cleanup: true
env:
  global:
  - DOCKER_USER=sjk5766
  - secure: I87q0F+5I9Kx/IH/ZMT1zQQlShAtNkdYQ5fxoUuPDgGOIcDfUhkXj5XWgO7NFkIthUo/n/u3b9w3YjmjG/YlTptjVPv7YaP2Guvc4eFs/ynx1P/jEmNby1OUgj26dy9pOs++anTog7KtIqDt7UqPX6oOVv556EbIl8bJoCaByLyEyH3KMSq87KWQu4yaL6F05lKAxPjLKqt/jaRliDS7Dq61CPQJllMt1d1zU94ZMWgJBztUW+agj+njwIOIldEPhn80OgAR5e5qnV/Dpk45sdiZbs2WKXWGghl4jVGuB8rdL0xteTxDlbZHP2sGFCyMduuZIgmhDaUc8LlqhWdWYFLFduGbYlI9PO2rNKSc4nZzIYbwljv8W0pkACe9O6ucFpXTK3pfVd7B9PHtHWu5fAVdhBeyK9TOi9106XDU/+3MCLZSS+aFfICDNFvmhj4QZjext1a1LpXBR22B4Fk7rSNUrO+XXic53rQ46l3DjP2qTnSaZOYS53Wjll5pIyxbXQZZMpMOGdQXgfB0jics2bYeVW7H67Br1xik9lQWakCpSr15uioVrfb90lq2926Fv/qZNEz3Lp2OAdvRbEq4PsGrq+hjoJeFORVmv2IXSsof43OZ7MW+1vPOIFEtGfB0d4wIZQ6I4rPmYHNcq/8qAKDYFUwnowxZpiB7MzB2Hds=
