language: node_js
node_js:
- lts/*
before_script:
- npm install
notifications:
  email:
    on_success: always
deploy:
  provider: heroku
  api_key:
    secure: UQNKwYBiMCadTzNiP9vbtXbRnLKDVlZa+FjFTG9cWNt3/nAdm5hkUwMrhMqQx1iNZVwrqFT7n+itreryUEbk/3vbQecAur1CZ4qi6VxmFkmXl1hA9C0FL/EWmzfK2HFw9KTiDyn+rPfjKgHIUrfjv2YQcnZMjAH7XCC05pcZgUtt7l2v4vrunbj7jBQqsq3ehAT74JzmIdXCcD8QgtZt78rp2XkM1GY0Rm2DuFM23/8wWAJPK0G67Fyrg94/TEFy+/bvG6US313oVHeMAFLTpX4JI2E29XK9cLrUGqkXd6s2MLudlFiKWwEWzQi7kAyGcGmdeEjNVTpOQhTqR2ALWqHWOB+xVQK2SFYdwWGohvM9vRfEoLKpiBCBajqvKQBZRsb1AVCyahStcdHmG/wfjxYDiUmUYux5IyviernssnvLhNer19RPvBUEv9Y5JK3LFHCqSHue0GY5/ATdr106YxyDojjP44vd/5CYigjntSZDHqhBwp8EJMf7mv9DSOmCLD318Bv2wB9gTmlUV35G8AqoKO9M/J4M/IYEPbdPOP/37mgRRD4ZM7kD8qJxHB4uWqC/pilikVEs1TYmaj/brbL0XmGznB8USdzflEYUYNzuGiW4W89g/5aRPKWQtuOM0ucEE2HhmAF1v4wcl9bqQtdibXhEUSI8hKLAKOCegdg=
  #skip_cleanup: true
env:
  global:
  - DOCKER_USER=sjk5766
  - secure: I87q0F+5I9Kx/IH/ZMT1zQQlShAtNkdYQ5fxoUuPDgGOIcDfUhkXj5XWgO7NFkIthUo/n/u3b9w3YjmjG/YlTptjVPv7YaP2Guvc4eFs/ynx1P/jEmNby1OUgj26dy9pOs++anTog7KtIqDt7UqPX6oOVv556EbIl8bJoCaByLyEyH3KMSq87KWQu4yaL6F05lKAxPjLKqt/jaRliDS7Dq61CPQJllMt1d1zU94ZMWgJBztUW+agj+njwIOIldEPhn80OgAR5e5qnV/Dpk45sdiZbs2WKXWGghl4jVGuB8rdL0xteTxDlbZHP2sGFCyMduuZIgmhDaUc8LlqhWdWYFLFduGbYlI9PO2rNKSc4nZzIYbwljv8W0pkACe9O6ucFpXTK3pfVd7B9PHtHWu5fAVdhBeyK9TOi9106XDU/+3MCLZSS+aFfICDNFvmhj4QZjext1a1LpXBR22B4Fk7rSNUrO+XXic53rQ46l3DjP2qTnSaZOYS53Wjll5pIyxbXQZZMpMOGdQXgfB0jics2bYeVW7H67Br1xik9lQWakCpSr15uioVrfb90lq2926Fv/qZNEz3Lp2OAdvRbEq4PsGrq+hjoJeFORVmv2IXSsof43OZ7MW+1vPOIFEtGfB0d4wIZQ6I4rPmYHNcq/8qAKDYFUwnowxZpiB7MzB2Hds=
ab377c04-4ae6-457d-afe5-7cb44c5b6e4d
