language: node_js
node_js:
- lts/*
before_script:
- npm install
notifications:
  email:
    on_success: always
deploy:
  provider: heroku
  api_key:
    secure: pCqKtNbQjhuoRp0hXB9bKxeeP+WFtYMm6fVDuJk7qgpXq8bm3aJi9J1jxkJj1ihE9YaTY24GjhHmZZbrMqMqFFVZ8wOmsUF9C1Rt9Lw0ZANoHoymjvGkPYS8/UxaxrVluHNr38ZMWBGZGwQCZ7Z83AEWps5cfrRG6xY6+0QUJKg/ccxGkiPeKI3v6vUuXfvA1c7y8i5UzI6NfhsZqRSLfhebVtv83dXljPp/0jl8EHyaQa63VrNbwxW7INXB5VhjdZyT3eoLVQylNtFTaWgMvy1AUjzsXmvOL0beP5OZqcIjOeQp7EmHcuy9T7KgVTc8wmTOsLu9ijL0RLnidSy0/TUYkAT7VkY/IKwwOnc+Y0Et58619vLeCD+rNci3VfjI3EKyR/EH2YuZQHJ+SVblCFwv0Fgw17MH4iDjOJI5Xnatwa0IXfs5lPQhAOghNXJb0Wjwu1v/LcDUQhqzB1yAj77bF6RCRi/GJ9QHziby0bScQDpvFssiuwqORY3BNDG1B3pc/U/e/yTIjG3CnpqfBotyS7Prw701uXAEN6aUoW8pZ+AX3iIrxkpjrCq9ybPvuGhAUOJ7OE2XsWlV6gCJP55NgvczWy1uuTnqNVF75B0dBs1rJUYyoya5crDjgb3i/qhRn7PdWZLkbagaps4qKZJdbyPn3NmFaEPWr/I0wLA=
  skip_cleanup: true
  app: sjk5766-travis
env:
  global:
  - DOCKER_USER=sjk5766
  - secure: I87q0F+5I9Kx/IH/ZMT1zQQlShAtNkdYQ5fxoUuPDgGOIcDfUhkXj5XWgO7NFkIthUo/n/u3b9w3YjmjG/YlTptjVPv7YaP2Guvc4eFs/ynx1P/jEmNby1OUgj26dy9pOs++anTog7KtIqDt7UqPX6oOVv556EbIl8bJoCaByLyEyH3KMSq87KWQu4yaL6F05lKAxPjLKqt/jaRliDS7Dq61CPQJllMt1d1zU94ZMWgJBztUW+agj+njwIOIldEPhn80OgAR5e5qnV/Dpk45sdiZbs2WKXWGghl4jVGuB8rdL0xteTxDlbZHP2sGFCyMduuZIgmhDaUc8LlqhWdWYFLFduGbYlI9PO2rNKSc4nZzIYbwljv8W0pkACe9O6ucFpXTK3pfVd7B9PHtHWu5fAVdhBeyK9TOi9106XDU/+3MCLZSS+aFfICDNFvmhj4QZjext1a1LpXBR22B4Fk7rSNUrO+XXic53rQ46l3DjP2qTnSaZOYS53Wjll5pIyxbXQZZMpMOGdQXgfB0jics2bYeVW7H67Br1xik9lQWakCpSr15uioVrfb90lq2926Fv/qZNEz3Lp2OAdvRbEq4PsGrq+hjoJeFORVmv2IXSsof43OZ7MW+1vPOIFEtGfB0d4wIZQ6I4rPmYHNcq/8qAKDYFUwnowxZpiB7MzB2Hds=
