language: node_js
node_js:
  - lts/*
before_script:
  - npm install
notifications:
  email:
    recipients:
      #- tjwjdrnr666@naver.com
      - wjdrnr6662@gmail.com
    #on_success: never # default: change
    #on_failure: always # default: always
