language: node_js
node_js:
- lts/*
before_script:
- npm install
notifications:
  email:
    on_success: always
deploy:
  provider: heroku
  api_key:
    secure: 7aCurHqIcjY2iUAO3nMxQjzmyUUPVMn1UD61d8Bz4XRXC4G50EbdA56694iU5dU4yooISMWeHWLHFaFNteG8cXjVQ603sigiyeUXC7ZCQnnZ62eK0XRAsKD0BfMNNCIM18GHCnvqt69A7jcY64YTbHJPU4VajhgOnqqCdEhEHcIZNl/0j0ruX6wwZ8TVg4AJFosuavd5yaZlIsEDQf7+vIhbjW+YYDOduLjjD98HvJ429iQMWUZnTHn3qeaA65hS31bHQwnD5BMX3x8bMhSDODJx6IxAQUbH1s2T1oyDruJ32xB1eWtPVByZ3LdlV6UBEIZfSSrqx5Ci5TGD0k765erF7zVDNGBPmVeAOnO4SLtSa8k2bR+c7NNcdtQQLrRjohoO5STPhX5l5B1rt07TOeVfjtc3S0Ad6VlP1xJs5yECkYiDVentp02olQo9ifNjtBwDA3htZ7tb5FgCtQdXXtbMy0Zz5b18AJn5HcpD7vSFeY1B6KdtqpmQZnQUvKFvu+9Se239Dg/DG8IgxiZYfrZwyvRD1CppP0EJEY2GdP0l7MVgXPR4pYzbaqiOTKYnTGfWrQiXU1PZKvQFInxDKO6hUwUhdUJWEKUkEXP8Ez6uV+EiOqChDakNVh+NrtorHlcesNDxqTuhjQUbixK+ATUmAyKmocbbCrbVxQUpOvo=
env:
  global:
  - DOCKER_USER=sjk5766
  - secure: I87q0F+5I9Kx/IH/ZMT1zQQlShAtNkdYQ5fxoUuPDgGOIcDfUhkXj5XWgO7NFkIthUo/n/u3b9w3YjmjG/YlTptjVPv7YaP2Guvc4eFs/ynx1P/jEmNby1OUgj26dy9pOs++anTog7KtIqDt7UqPX6oOVv556EbIl8bJoCaByLyEyH3KMSq87KWQu4yaL6F05lKAxPjLKqt/jaRliDS7Dq61CPQJllMt1d1zU94ZMWgJBztUW+agj+njwIOIldEPhn80OgAR5e5qnV/Dpk45sdiZbs2WKXWGghl4jVGuB8rdL0xteTxDlbZHP2sGFCyMduuZIgmhDaUc8LlqhWdWYFLFduGbYlI9PO2rNKSc4nZzIYbwljv8W0pkACe9O6ucFpXTK3pfVd7B9PHtHWu5fAVdhBeyK9TOi9106XDU/+3MCLZSS+aFfICDNFvmhj4QZjext1a1LpXBR22B4Fk7rSNUrO+XXic53rQ46l3DjP2qTnSaZOYS53Wjll5pIyxbXQZZMpMOGdQXgfB0jics2bYeVW7H67Br1xik9lQWakCpSr15uioVrfb90lq2926Fv/qZNEz3Lp2OAdvRbEq4PsGrq+hjoJeFORVmv2IXSsof43OZ7MW+1vPOIFEtGfB0d4wIZQ6I4rPmYHNcq/8qAKDYFUwnowxZpiB7MzB2Hds=
services:
- docker
