language: node_js
node_js:
- lts/*
before_script:
- npm install
notifications:
  email:
    on_success: always
deploy:
  provider: heroku
  api_key:
    secure: 5LYPtwNBUvlpcq43iTr0+i19Ozg1aJwmMPAskXVPwrudWfs235oEKPRHy8ydg3kCh28xcqtV8k3O75CYEnKlA8zPxZDge8eV4eU/MYkI6LA52RX/wck0qlN1kT+Sxlx+WRCIvFGdHC+K/RYR08W6YUWGJgoLCZrOT1y/nD3VKv6E6NFtwHHb/jHr5JF39RWeUjvYNJyWP2+rfDp2F+4oh3sEjdfsHZMhYylg3yyni2gqgwYWv5TwSAWlNfbs25Mpipnr3Ny0SAuh1GdBdmnNW7gVr5DmWUgYctMsZRWIv2zDtsbQyc8m2JT6IBi8GtqM2vh4Y6c+BeR4Ngq4o14Wx+gn56bfGAIvr8W0W10mqvLBu9M61qGXU/abNiv6xwGtjEFI5oJwP59aUAFuPtO6IjkzJjCssPAOxY1w3ZU4x51yQXzdfck0f/CkqCwJD1vQiBrUqQRilfB9CJweWNq9malbCPluHHJNCm+t1V/3q3J9FZbuqbQBJxGFL+amDx495NPp2Q9OVETBcEFefZpK6rrtNI6zDgbFHT23U3BloU4wo+PpWb+hvqcQ1MzzGmsvXXfDtUO0/O7/P86DU/sVRAjx9tXiaDEidkUZi1yOEXiYyBRGvehAUNthqLlaxYVkGWxJyCz8WYCCe30g766oTDcQhmJSxK2WZwCGfdZbv8I=
env:
  global:
  - DOCKER_USER=sjk5766
  - secure: I87q0F+5I9Kx/IH/ZMT1zQQlShAtNkdYQ5fxoUuPDgGOIcDfUhkXj5XWgO7NFkIthUo/n/u3b9w3YjmjG/YlTptjVPv7YaP2Guvc4eFs/ynx1P/jEmNby1OUgj26dy9pOs++anTog7KtIqDt7UqPX6oOVv556EbIl8bJoCaByLyEyH3KMSq87KWQu4yaL6F05lKAxPjLKqt/jaRliDS7Dq61CPQJllMt1d1zU94ZMWgJBztUW+agj+njwIOIldEPhn80OgAR5e5qnV/Dpk45sdiZbs2WKXWGghl4jVGuB8rdL0xteTxDlbZHP2sGFCyMduuZIgmhDaUc8LlqhWdWYFLFduGbYlI9PO2rNKSc4nZzIYbwljv8W0pkACe9O6ucFpXTK3pfVd7B9PHtHWu5fAVdhBeyK9TOi9106XDU/+3MCLZSS+aFfICDNFvmhj4QZjext1a1LpXBR22B4Fk7rSNUrO+XXic53rQ46l3DjP2qTnSaZOYS53Wjll5pIyxbXQZZMpMOGdQXgfB0jics2bYeVW7H67Br1xik9lQWakCpSr15uioVrfb90lq2926Fv/qZNEz3Lp2OAdvRbEq4PsGrq+hjoJeFORVmv2IXSsof43OZ7MW+1vPOIFEtGfB0d4wIZQ6I4rPmYHNcq/8qAKDYFUwnowxZpiB7MzB2Hds=
