language: node_js
node_js:
- lts/*
before_script:
- npm install
notifications:
  email:
    on_success: always
deploy:
  provider: heroku
  api_key:
    secure: PCYpYGyJtig73EoKil+Do18AIW+i8wGGfv5ramHzxUTbs7vtIfEu4HSEYWfNcl1+OvjMLxiW9RvQSqUkYSrYyLdHqcWvWcPc4GlVcJLXidaG57MvaaTx4Z4yqAvvtX5tK8yamxPkek97QkGNCwxwr/4nyRdleFiEo/FNP9GlpQNUaLo6kYkfCJSVERNzn1nqn+y6ICklUcyV/ILWFoc+l4zlAaE822GGhheHISEn8BXSUuUCzVnWDYpyqfGpW2rqnVscb3adr6AqAFT+pJqzLAeNYK9X4R0XAvnYAEB5nrmVyToFGmvqX1rRIQ9LKcK2giYw9qHVEwxXOMx6dNTlZJNuHxebqHh27yw1njIBxVE2jPG3OPKOWU8lwoUUucjFCF4FV3PiUAUSoEQeN6JE1OdyBj9ZneYvOP8+ITT0YdehPZL1z94psYl0F/DkQvfdHMkZTplbTkgJqBplcYVk10xUhFXHfmx+FBufawxYs3V3kGyCB6caYdN7ax2PnlmLSBzwdTaJgAsynvC4lGdm4wtcHC0I4gK4fu/wgdvaUBmOuwotjyMh5etgQjRlQMSaUwBcaOU8Jdj+O8DBJU2QZRRvvCVO8hQaoXlZdAxz4GTLjk7LYJqTv1rqcGg4Z8mhRRF2JbC7DaZGd84HlBR60IImg3Zk/cjqP9RyrVR+CYM=
  skip_cleanup: true
  app: sjk5766-travis
env:
  global:
  - DOCKER_USER=sjk5766
  - secure: I87q0F+5I9Kx/IH/ZMT1zQQlShAtNkdYQ5fxoUuPDgGOIcDfUhkXj5XWgO7NFkIthUo/n/u3b9w3YjmjG/YlTptjVPv7YaP2Guvc4eFs/ynx1P/jEmNby1OUgj26dy9pOs++anTog7KtIqDt7UqPX6oOVv556EbIl8bJoCaByLyEyH3KMSq87KWQu4yaL6F05lKAxPjLKqt/jaRliDS7Dq61CPQJllMt1d1zU94ZMWgJBztUW+agj+njwIOIldEPhn80OgAR5e5qnV/Dpk45sdiZbs2WKXWGghl4jVGuB8rdL0xteTxDlbZHP2sGFCyMduuZIgmhDaUc8LlqhWdWYFLFduGbYlI9PO2rNKSc4nZzIYbwljv8W0pkACe9O6ucFpXTK3pfVd7B9PHtHWu5fAVdhBeyK9TOi9106XDU/+3MCLZSS+aFfICDNFvmhj4QZjext1a1LpXBR22B4Fk7rSNUrO+XXic53rQ46l3DjP2qTnSaZOYS53Wjll5pIyxbXQZZMpMOGdQXgfB0jics2bYeVW7H67Br1xik9lQWakCpSr15uioVrfb90lq2926Fv/qZNEz3Lp2OAdvRbEq4PsGrq+hjoJeFORVmv2IXSsof43OZ7MW+1vPOIFEtGfB0d4wIZQ6I4rPmYHNcq/8qAKDYFUwnowxZpiB7MzB2Hds=
