version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports: 
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  express1:
    build:
      context: ./server
    container_name: express1
    expose:
      - "3000"
    volumes:
      - ./source/express1:/source
      - /source/node_modules
    restart: "unless-stopped"
  express2:
    build:
      context: ./server
    container_name: express2
    expose:
      - "3000"
    volumes:
      - ./source/express2:/source
      - /source/node_modules
    restart: "unless-stopped"
